name: Workflow & Review
on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build step running"
  staging_deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to staging environment"
  staging_testing:
    needs: staging_deployment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run tests on staging environment"
  automation_approval:
    needs: staging_testing
    if: startsWith(github.ref_name, 'release/')
    uses: ./.github/workflows/lark-automation-approval.yaml
    with:
      SERVICE_NAME: octolark
      TEAM: ${{ vars.SYSTEMS }}
    permissions:
      id-token: write
      contents: write
    secrets: inherit
  approval_needed:
    needs: automation_approval
    runs-on: ubuntu-latest
    environment: production   # 👈 requires approval if 'production' has reviewers set
    steps:
      - run: echo "This job will only continue after approval"
  production_deployment:
    needs: approval_needed
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment approved ✅"
